@startuml diagrama_classe

title Diagrama de Classes

class MiniGame{
    -powerOn: Boolean 
    -selectGame: String
    -volume: Integer
    +construto(powerOn, selectGame, volume)
    +ligar(powerOn)
    +selecionarGame(selectGame)
    +volumeUp(volume)
    +volumeDown(volume)
}

